"use client";
import { useEffect,useState } from "react"; import { useRouter } from "next/navigation"; import { clearPlayerState } from "@/lib/playerState";
function HomePage(){const [book,setBook]=useState(null),[code,setCode]=useState(""),[name,setName]=useState(""),[err,setErr]=useState("");const router=useRouter();
 useEffect(()=>{const readLocal=()=>{try{return typeof window!=='undefined'?JSON.parse(window.localStorage.getItem('seoul-choice-editor-stories')||'[]'):[]}catch{return[]}};Promise.all([fetch('/api/story').then(r=>r.json()).catch(()=>({stories:[]})),Promise.resolve(readLocal())]).then(([server,local])=>{const merged=[...(server.stories||[])];for(const item of local){if(!merged.some(x=>x.id===item.id))merged.push(item)}setBook({stories:merged,activeStoryId:server.activeStoryId||merged[0]?.id||null})}).catch(()=>setBook({stories:[]}))},[]);
 function go(e){e.preventDefault();if(!name.trim()){setErr("이름을 입력하세요.");return}const stories=book?.stories||[];const entered=code.trim();const env=process.env.NEXT_PUBLIC_PLAY_CODE||"";let s=stories.find(x=>(x.accessCodes||[]).includes(entered));if(!s&&env&&entered===env)s=stories.find(x=>x.id===book.activeStoryId)||stories[0];if(!s&&!entered&&stories.length===1&&!(stories[0].accessCodes||[]).length)s=stories[0];if(!s){setErr(stories.length>1?"스토리 접근 코드를 입력해주세요.":"스토리 접근 코드가 올바르지 않습니다.");return}clearPlayerState(); sessionStorage.setItem('draft-player-name',name.trim());sessionStorage.setItem('play-story-id',s.id);sessionStorage.setItem('new-game','1');router.push('/faction')}
 if(!book)return <main className="playMain"><p>불러오는 중...</p></main>;
 const needsCode=(book.stories||[]).some(s=>(s.accessCodes||[]).length>0)||!!process.env.NEXT_PUBLIC_PLAY_CODE;
 return <main className="playMain" style={{textAlign:'center',paddingTop:90}}><h1 style={{fontSize:22,marginBottom:12}}>텍스트 선택지 게임</h1><p style={{color:'#777',fontSize:13,marginBottom:30}}>이름과 스토리 접근 정보를 입력하세요.</p><form onSubmit={go} style={{maxWidth:360,margin:'0 auto'}}><input value={name} onChange={e=>setName(e.target.value)} placeholder="플레이어 이름" style={{width:'100%',marginBottom:10}}/>{needsCode&&<input value={code} onChange={e=>setCode(e.target.value)} placeholder="스토리 접근 코드" style={{width:'100%',marginBottom:10}}/>}<button type="submit" style={{width:'100%',padding:11}}>시작</button></form>{err&&<p style={{color:'#b33',fontSize:12,marginTop:10}}>{err}</p>}</main>}
export default HomePage;
